import { cookies } from 'next/headers';
import { db, secret } from '@/lib/cloudflare';
const SESSION_COOKIE='marams_cafe_admin',CSRF_COOKIE='marams_cafe_admin_csrf';
const enc=new TextEncoder(),now=()=>Date.now();
async function hash(v:string){const h=await crypto.subtle.digest('SHA-256',enc.encode(v));return [...new Uint8Array(h)].map(b=>b.toString(16).padStart(2,'0')).join('');}
function randomToken(bytes=32){const b=new Uint8Array(bytes);crypto.getRandomValues(b);return btoa(String.fromCharCode(...b)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function safeEqual(a:string,b:string){if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0;}
async function cleanExpired(){await db().prepare('DELETE FROM admin_sessions WHERE expires_at<=?').bind(now()).run();}
export function validPassword(value:string){const expected=secret('ADMIN_PASSWORD');return Boolean(expected)&&safeEqual(value,expected);}
export function clientKey(req:Request){return req.headers.get('cf-connecting-ip')||req.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||'unknown';}
export async function loginAllowed(key:string){const r=await db().prepare('SELECT blocked_until FROM admin_login_attempts WHERE client_key=?').bind(key).first<any>();return !r||Number(r.blocked_until||0)<=now();}
export async function recordLoginFailure(key:string){const t=now(),windowMs=600000,blockMs=900000,r=await db().prepare('SELECT * FROM admin_login_attempts WHERE client_key=?').bind(key).first<any>();let started=t,failures=1;if(r&&t-Number(r.window_started)<windowMs){started=Number(r.window_started);failures=Number(r.failures)+1;}const blocked=failures>=5?t+blockMs:0;await db().prepare('INSERT INTO admin_login_attempts(client_key,window_started,failures,blocked_until) VALUES(?,?,?,?) ON CONFLICT(client_key) DO UPDATE SET window_started=excluded.window_started,failures=excluded.failures,blocked_until=excluded.blocked_until').bind(key,started,failures,blocked).run();return{failures,blockedUntil:blocked};}
export async function clearLoginFailures(key:string){await db().prepare('DELETE FROM admin_login_attempts WHERE client_key=?').bind(key).run();}
export async function createAdminSession(){await cleanExpired();const token=randomToken(32),csrf=randomToken(24),created=now(),expires=created+8*3600000;await db().prepare('INSERT INTO admin_sessions(token_hash,csrf_hash,created_at,expires_at) VALUES(?,?,?,?)').bind(await hash(token),await hash(csrf),created,expires).run();const c=await cookies();c.set(SESSION_COOKIE,token,{httpOnly:true,sameSite:'strict',secure:true,path:'/',maxAge:28800});c.set(CSRF_COOKIE,csrf,{httpOnly:false,sameSite:'strict',secure:true,path:'/',maxAge:28800});return{csrfToken:csrf,expiresAt:new Date(expires).toISOString()};}
export async function isAdmin(){await cleanExpired();const c=await cookies(),token=c.get(SESSION_COOKIE)?.value||'';if(!token)return false;const r=await db().prepare('SELECT expires_at FROM admin_sessions WHERE token_hash=?').bind(await hash(token)).first<any>();return Boolean(r&&Number(r.expires_at)>now());}
export async function requireAdmin(){if(!await isAdmin())throw new Error('UNAUTHORIZED');}
export async function requireAdminCsrf(req:Request){if(!await isAdmin())return false;const c=await cookies(),token=c.get(SESSION_COOKIE)?.value||'',csrfCookie=c.get(CSRF_COOKIE)?.value||'',csrfHeader=req.headers.get('x-admin-csrf')||'';if(!csrfCookie||!csrfHeader||!safeEqual(csrfCookie,csrfHeader))return false;const r=await db().prepare('SELECT csrf_hash FROM admin_sessions WHERE token_hash=?').bind(await hash(token)).first<any>();return Boolean(r&&safeEqual(String(r.csrf_hash),await hash(csrfHeader)));}
export async function clearAdminSession(){const c=await cookies(),token=c.get(SESSION_COOKIE)?.value||'';if(token)await db().prepare('DELETE FROM admin_sessions WHERE token_hash=?').bind(await hash(token)).run();c.set(SESSION_COOKIE,'',{httpOnly:true,sameSite:'strict',secure:true,path:'/',maxAge:0});c.set(CSRF_COOKIE,'',{httpOnly:false,sameSite:'strict',secure:true,path:'/',maxAge:0});}
export async function getCsrfForCurrentSession(){if(!await isAdmin())return null;return (await cookies()).get(CSRF_COOKIE)?.value||null;}
