import { db, secret } from '@/lib/cloudflare';
export type AnamConfig={apiKey:string;avatarId:string;agentId:string;voiceId:string;llmId:string;baristaName:string};
const enc=new TextEncoder(),dec=new TextDecoder();
const defaults=():AnamConfig=>({apiKey:secret('ANAM_API_KEY'),avatarId:secret('ANAM_AVATAR_ID')||'f01c2101-bdf3-4766-9f2a-ed07fa5fe139',agentId:secret('ANAM_AGENT_ID')||'c38d14db-f0be-457a-90b0-87351d210591',voiceId:secret('ANAM_VOICE_ID')||'c48c4dd9-5050-11f1-9076-5e955d484d11',llmId:secret('ANAM_LLM_ID')||'a7cf662c-2ace-4de1-a21e-ef0fbf144bb7',baristaName:secret('ANAM_BARISTA_NAME')||"Maram · Maram's Cafe"});
async function key(){const s=secret('ADMIN_CONFIG_ENCRYPTION_KEY')||secret('ADMIN_PASSWORD');if(!s)throw new Error('ADMIN_CONFIG_ENCRYPTION_KEY is required');const h=await crypto.subtle.digest('SHA-256',enc.encode(s));return crypto.subtle.importKey('raw',h,'AES-GCM',false,['encrypt','decrypt']);}
const b64=(a:Uint8Array)=>btoa(String.fromCharCode(...a)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const unb64=(s:string)=>{s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0));};
async function encrypt(v:string){const iv=crypto.getRandomValues(new Uint8Array(12)),data=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},await key(),enc.encode(v)));return `v2.${b64(iv)}.${b64(data)}`;}
async function decrypt(v:string){if(!v.startsWith('v2.'))return v;const[,i,d]=v.split('.');return dec.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(i)},await key(),unb64(d)));}
export async function getAnamConfig(){const out=defaults();for(const k of Object.keys(out) as (keyof AnamConfig)[]){const r=await db().prepare('SELECT value FROM app_config WHERE key=?').bind('anam.'+k).first<any>();if(r)try{out[k]=await decrypt(String(r.value));}catch{}}return out;}
export async function saveAnamConfig(input:Partial<AnamConfig>){const allowed:(keyof AnamConfig)[]=['apiKey','avatarId','agentId','voiceId','llmId','baristaName'],d=db(),stmts:D1PreparedStatement[]=[];for(const k of allowed){if(typeof input[k]==='string'&&String(input[k]).trim())stmts.push(d.prepare('INSERT INTO app_config(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at').bind('anam.'+k,await encrypt(String(input[k]).trim()),Date.now()));}if(stmts.length)await d.batch(stmts);return getAnamConfig();}
export async function publicAnamConfig(){const c=await getAnamConfig();return{...c,apiKey:'',apiKeyConfigured:Boolean(c.apiKey),apiKeyHint:c.apiKey?`••••${c.apiKey.slice(-4)}`:''};}
